apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
# kubectl expose pod nginx-pod --type=NodePort --name=nginx-svc --port=80 --target-port=80
