apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.27.0
      ports:
        - containerPort: 80

# equivalent command:
# kubectl run nginx-pod --image=nginx:1.27.0 --port=80 --labels="app=nginx"