pipeline {
    agent any
	tools {
		nodejs 'NodeJS 25.2.1'
	}
	environment {
		DOCKER_HUB_REPO = 'jeff541/jenkins_argocd'
	}
    stages {
        stage('Build') {
            steps {
          git branch: 'main', credentialsId: 'Git-Ops-Token', url: 'https://github.com/jeff541/devops_project.git'  }
        }
        stage('Install Node Dependencies') {
            steps {
                echo 'Installing Node Dependencies....'
				    dir('Jenkins-ArgoCD') {   
                    sh 'npm install'
                }
            }
        }
        stage('Build the Docker Image') {
            steps {
                echo 'Building the Docker Image....'
				
				    dir('Jenkins-ArgoCD') {   
			script {
                  
           sh '''
        docker build -t jeff541/jenkins_argocd:latest .
      '''
						}
                }
            }
        }
    }
}