pipeline {
    agent any
	tools {
		nodejs 'NodeJS 25.2.1'
	}
	environment {
		DOCKER_HUB_REPO = 'jeff541/jenkins_argocd'
        DOCKER_HUB_CREDENTIALS_ID = 'Dockerhub'
	}
    stages {
        stage('Build') {
            steps {
          git branch: 'main', credentialsId: 'Git-Ops-Token', url: 'https://github.com/jeff541/devops_project.git'  }
        }
        stage('Install Node Dependencies') {
            steps {
                echo 'Installing Node Dependencies....'
				    dir('Jenkins-ArgoCD') {   
                    sh 'npm install'
                }
            }
        }
        stage('Build the Docker Image') {
            steps {
                echo 'Building the Docker Image....'
				
				    dir('Jenkins-ArgoCD') {   
			script {
                  
           sh '''
        docker build -t ${DOCKER_HUB_REPO}:latest .
      '''
						}
                }
            }
        }
        stage('Trivy Scan'){
        steps {
                //    sh 'trivy image jeff541/jenkins_argocd:latest --severity HIGH,CRITICAL --no-progress --format table -o trivy-scan-report.txt'
            sh 'trivy image jeff541/jenkins_argocd:latest --skip-db-update --severity HIGH,CRITICAL --no-progress --format table -o trivy-scan-report.txt'
        }
    }
    	stage('Push Image to DockerHub'){
			steps {
				script {
					echo 'pushing docker image to DockerHub...'
					docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_HUB_CREDENTIALS_ID}"){
						dockerImage.push('latest')
						}
					}
				}
			}
    }
}