pipeline {
    agent any
	tools {
		nodejs 'NodeJS 25.2.1'
		docker 'Docker'
	}
    stages {
        stage('Build') {
            steps {
                git branch: 'main', credentialsId: 'GitOps-Token-Github', url: 'https://github.com/jeff541/devops_project.git'
            }
        }
        stage('Install Node Dependencies') {
            steps {
                echo 'Installing Node Dependencies....'
				    dir('Jenkins-ArgoCD') {   
                    sh 'npm install'
                }
            }
        }
        stage('Build the Docker Image') {
            steps {
                echo 'Building the Docker Image....'
				
				    dir('Jenkins-ArgoCD') {   
                    sh 'docker build -t jeff541/devops_project:latest .'
                }
            }
        }
    }
}